function data = RapidCastParse( filename )
%RapidCastPARSE Parses a .vp2 data file from a Rapid Cast system with
%Valeport CTD recorder
% Built based on IMOS toolbox code for SBESMParse.m
% It makes use of a lower level
% function readrapidvp2. The files consist of up to
% three sections:
%
%   - instrument header - header information as retrieved from the instrument.
%                         These lines are prefixed with '*'.
%   - processed header  - header information generated by SBE Data Processing.
%                         These lines are prefixed with '#'.
%   - data              - Rows of data.
%
% This function reads in the header sections, and delegates to the two file
% specific sub functions to process the data.
%
% Inputs:
%   filename    - cell array of files to import (only one supported).
%   mode        - Toolbox data type mode ('profile' or 'timeSeries').
%
% Outputs:
%   sample_data - Struct containing sample data.
%
% Author: Brad Morris <brad.morris@unsw.edu.au>
%   :Bec Cowley

%
% Copyright (c) 2009, eMarine Information Infrastructure (eMII) and Integrated
% Marine Observing System (IMOS).
% All rights reserved.
%
% Redistribution and use in source and binary forms, with or without
% modification, are permitted provided that the following conditions are met:
%
%     * Redistributions of source code must retain the above copyright notice,
%       this list of conditions and the following disclaimer.
%     * Redistributions in binary form must reproduce the above copyright
%       notice, this list of conditions and the following disclaimer in the
%       documentation and/or other materials provided with the distribution.
%     * Neither the name of the eMII/IMOS nor the names of its contributors
%       may be used to endorse or promote products derived from this software
%       without specific prior written permission.
%
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
% AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
% IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
% ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
% LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
% CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
% SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
% INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
% CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
% ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
% POSSIBILITY OF SUCH DAMAGE.
%
narginchk(1,2);

[~, ~, ext] = fileparts(filename);

if strcmpi(ext, '.vp2')
    % read in every line in the file, separating
    % them out into each of the three sections
    try
        fid = fopen(filename, 'rt');
        fileContent = textscan(fid, '%s', 'Delimiter', '', 'Whitespace', '');
        fclose(fid);
        
        fileContent = fileContent{1};
        
        % Header is labelled as [HEADER]
        iInst = 1;
        ihead = find(cellfun(@isempty,strfind(fileContent,'[HEADER]')) == 0);
        icols = find(cellfun(@isempty,strfind(fileContent,'[COLUMNS]')) == 0);
        idata = find(cellfun(@isempty,strfind(fileContent,'[DATA]')) == 0);
        
        %instrument header information
        instHeaderLines = fileContent(ihead+1:icols-1);
        
        % and then the proc header with '#'
        procHeaderLines = fileContent(icols+1:idata-1);
        
        % and then we assume the data comes after one more '*' line so we
        % add +1 below
        dataLines = fileContent(idata + 3 :end);
    catch e
        if fid ~= -1, fclose(fid); end
        rethrow(e);
    end
    
    % read in the raw instrument header
    instHeader = parseInstrumentHeader(instHeaderLines);
    procHeader = parseProcessedHeader( procHeaderLines);
    
    %read teh data
    data = readRapidCast(dataLines, procHeader);
    
    % create sample data struct,
    % and copy all the data in
    
    data.toolbox_input_file  = filename;
    data.meta.instHeader     = instHeader;
    data.meta.procHeader     = procHeader;
end
end

function header = parseInstrumentHeader(headerLines)
%PARSEINSTRUMENTHEADER Parses the header lines from a SBE19/37 .cnv file.
% Returns the header information in a struct.
%
% Inputs:
%   headerLines - cell array of strings, the lines of the header section.
%
% Outputs:
%   header      - struct containing information that was in the header
%                 section.
%
header = struct;

%just pull out a few things for these rapid casts
serialExpr= 'SerialNumber=';
timeTareExpr= 'TareTimeStamp=';
timeDataExpr = 'DataStartTime=';
minTimeExpr ='MinTime=';
maxTimeExpr ='MaxTime=';
latExpr = 'Latitude=';
lonExpr = 'Longitude=';
flagExpr = 'LoggerFlag=';
exprs = {...
    serialExpr   minTimeExpr     ...
    maxTimeExpr  latExpr    ...
    lonExpr  flagExpr ...
    timeTareExpr  timeDataExpr};

  
    % try each of the expressions
    for m = 1:length(exprs)
        
        % until one of them matches
        imatch = strmatch(exprs{m},headerLines);
        if ~isempty(imatch)
            ind = strfind(headerLines{imatch},'=');
            
            % yes, ugly, but easiest way to figure out which regex we're on
            switch m
                
                % new style header
                case 1
                    header.instrument_serial_no = headerLines{imatch}(ind+1:end);
                    
                    % scan
                case 2
                    header.minTime = headerLines{imatch}(ind+1:end);
                    
                    % mem
                case 3
                    header.maxTime   = headerLines{imatch}(ind+1:end);
                    
                    % sample
                case 4
                    header.latitude        = str2double(headerLines{imatch}(ind+1:end));
                    
                    % mode
                case 5
                    header.longitude        = str2double(headerLines{imatch}(ind+1:end));
                    
                    % badFlag
                 case 6
                    header.badFlag        = headerLines{imatch}(ind+1:end);
                    % badFlag
                 case 7
                    header.tareTime        = headerLines{imatch}(ind+1:end);
                 case 8
                    header.startDataTime        = headerLines{imatch}(ind+1:end);
           end
        end
    end
end

function header = parseProcessedHeader(headerLines)
%PARSEPROCESSEDHEADER Parses the data contained in the header added by SBE
% Data Processing. This includes the column layout of the data in the .cnv
% file.
%
% Inputs:
%   headerLines - Cell array of strings, the lines in the processed header
%                 section.
%
% Outputs:
%   header      - struct containing information that was contained in the
%                 processed header section.
%

header = struct;
header.columns = {};

nameExpr = '(\S*)=.*';

for k = 1:length(headerLines)
    
    % try name expr
    tkns = regexp(headerLines{k}, nameExpr, 'tokens');
    if ~isempty(tkns)
        if ~isempty(strfind(tkns{1}{1},'Date/Time'))
            header.columns{end+1} = 'Date';
            header.columns{end+1} = 'Time';
            continue
        else
            header.columns{end+1} = tkns{1}{1};
            continue;
        end
    end
    
end
end

function time = genTimestamps(instHeader, procHeader, data)
%GENTIMESTAMPS Generates timestamps for the data. Horribly ugly. I shouldn't
% have to have a function like this, but the .cnv files do not necessarily
% provide timestamps for each sample.
%

% time may have been present in the sample
% data - if so, we don't have to do any work
if isfield(data, 'TIME'), time = data.TIME; return; end

% To generate timestamps for the CTD data, we need to know:
%   - start time
%   - sample interval
%   - number of samples
%
% The SBE19 header information does not necessarily provide all, or any
% of this information. .
%
start    = 0;
interval = 0.25;

% figure out number of samples by peeking at the
% number of values in the first column of 'data'
f = fieldnames(data);
nSamples = length(data.(f{1}));

% try and find a start date - use castDate if present
if isfield(instHeader, 'castDate')
    start = instHeader.castDate;
else
    if isfield(procHeader, 'startTime')
        start = procHeader.startTime;
    end
end

% if scanAvg field is present, use it to determine the interval
if isfield(instHeader, 'scanAvg')
    interval = (0.25 * instHeader.scanAvg) / 86400;
else
    if isfield(procHeader, 'interval')
        switch procHeader.resolution
            case 'seconds'
                interval = procHeader.interval / (60*60*24);
            case 'minutes'
                interval = procHeader.interval / (60*24);
            case 'hours'
                interval = procHeader.interval / 24;
            case 'days'
                interval = procHeader.interval;
        end
    end
end

% if one of the columns is 'Scan Count', use the
% scan count number as the basis for the timestamps
if isfield(data, 'ScanCount')
    
    time = ((data.ScanCount - 1) ./ 345600) + cStart;
    
    % if scan count is not present, calculate the
    % timestamps from start, end and interval
else
    
    time = (start:interval:start + (nSamples - 1) * interval)';
end
end
